name: {{project_name}}
description: "{{description}}"
publish_to: 'none'
version: {{version}}

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Firebase
  firebase_core: ^3.8.1
  firebase_analytics: ^11.3.5
  firebase_app_check: ^0.3.2+1
  firebase_remote_config: ^5.1.5

  # In-app purchases
  in_app_purchase: ^3.2.0

  # Navigation
  go_router: ^14.6.2

  # Localization
  intl: ^0.20.2

  # Storage
  shared_preferences: ^2.3.3

  # Utils
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  generate: true


